### ISSUE TITLE
Not an issue -- just thanks

### ISSUE THREAD

**Issue by samipfjo** [Lemuura/It-Takes-Two-Autosplitter#1]
Hey, wanted to swing by and thank you for posting this on GH. I'm not a runner, but it gave me an easy to use list of internal map names that allowed me to recreate a lost save file without having to run `strings` on massive binaries. You saved the night for my wife and I, and I appreciate you <3

**Comment by Lemuura** [comment]
Haha not what I expected to see, happy it helped <3 hope you have fun with the game :D
